name: firstworkflow

on: 
  push:
    branches:
      - main

env:
  MY_NAME: "Syed_Muzzammil"

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo "Hello ${{ env.MY_NAME }}"
    
    - name: get comments from env ${{ env.MY_NAME }}
      run: |
        echo "Awesome"
        echo "my name is ${{ env.MY_NAME }}"
        echo "Nice"