name: firstjobn
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo "Hello, world!"
    - name: Run a multi-line script
      run: |
        echo "First Output"
        echo "Second Output"
        echo "Third Output"
        echo "Fourth Output"
