name: firstworkflow
on: workflow_dispatch
jobs:
  first-jon:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo This is a multi-line script
        echo It is a very simple script